### ISSUE TITLE
panic when running inamedparam

### ISSUE THREAD

**Issue by esinek** [macabu/inamedparam#1]
ERRO [runner] Panic: inamedparam: package "model" (isInitialPkg: true, needAnalyzeSource: true): runtime error: index out of range [0] with length 0: goroutine 94874 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:109 +0x224
panic({0x101c32000?, 0x14074442138?})
        runtime/panic.go:914 +0x218
github.com/macabu/inamedparam.run.func1({0x101ca41e0?, 0x14036763c50?})
        github.com/macabu/inamedparam@v0.1.2/inamedparam.go:39 +0x364
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0x1402c265d28, {0x14017167ce0?, 0x1?, 0x30000007d?}, 0x14074275cd0)
        golang.org/x/tools@v0.14.0/go/ast/inspector/inspector.go:82 +0x98
github.com/macabu/inamedparam.run(0x140744356c0)
        github.com/macabu/inamedparam@v0.1.2/inamedparam.go:27 +0xa0
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x14010da2a70)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:195 +0x900
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:113 +0x20
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x14002ce91d0, {0x1018309ac, 0xb}, 0x1401a10af30)
        github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x10123fcf0?)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:112 +0x78
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x14010da2a70)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb0
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 3533
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x184 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: inamedparam: package "model" (isInitialPkg: true, needAnalyzeSource: true): runtime error: index out of range [0] with length 0 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: inamedparam: package "model" (isInitialPkg: true, needAnalyzeSource: true): runtime error: index out of range [0] with length 0

**Comment by macabu** [comment]
Hi @esinek , thanks for reporting. Could you please share a minimal reproducible example?

I can see what the problem is, but I was not able to find an example to trigger it.  

-- 
edit: I released a generic fix for the issue on `v0.1.3`
